applications:
- api_domain: stagingpartner.lrinternal.com
  application_name: Test12
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: .jit/openapi_spec.yaml
  type: api
deployment:
  environments:
  - stage
plan_items:
  item-api-security:
    deployment:
      configuration:
      - Test12
      tags:
      - stage
      trigger: deployment
